### ISSUE TITLE
Non-Monotonic Predictions

### ISSUE THREAD

**Issue by peterpaohuang** [niklasnolte/MonotOneNorm#11]
Hi Niklas and Ouail,

I am running into an issue where during training of these monotonic NNs, the predictions are not coming out monotonic whenever the Lipschitz constant is >1. 

Specifically, I am training a model similar to the "RobustModel" in https://github.com/niklasnolte/MonotonicNetworks/blob/main/Examples/Examples_paper.ipynb, except with a Lipschitz constant of 100.

I attached the barebones code (below) and the associated training data (x.pt and gt.pt in [data.zip](https://github.com/niklasnolte/MonotonicNetworks/files/15451375/data.zip)) that reproduces this non-monotonic issue. The code will raise an exception whenever a prediction from the model is non-monotonic (usually around 100-200 epochs into training). Please let me know if I am missing something. 

Thank you in advance for your time and help!

Code:
```
import monotonicnetworks as lmn

import torch
import torch.nn as nn
import torch.optim as optim

from tqdm import tqdm
    
class MonotonicNN(nn.Module):
    def __init__(self):
        super(MonotonicNN, self).__init__()

        lnn = torch.nn.Sequential(
            lmn.LipschitzLinear(1, 512, kind="one", lipschitz_const=100),
            lmn.GroupSort(2),
            lmn.LipschitzLinear(512, 512, kind="one", lipschitz_const=100),
            lmn.GroupSort(2),
            lmn.LipschitzLinear(512, 512, kind="one", lipschitz_const=100),
            lmn.GroupSort(2),
            lmn.LipschitzLinear(512, 1, kind="one", lipschitz_const=100),
        )

        self.nn = lmn.MonotonicWrapper(lnn, lipschitz_const=100)
        self.loss = nn.MSELoss()
        
    def forward(self, x):
        x = self.nn(x)
        return x
    
    def is_monotonoic(self, ts):
        for i in range(1,len(ts)):
            if ts[i - 1] > ts[i]:
                print(ts[i - 1], ts[i])
                return False
        return True
            
    def step(self, x, gt):
        y_hat = self.forward(x)
        if not self.is_monotonoic(y_hat):
            raise

        loss = self.loss(y_hat, gt)
        return loss

    def training_step(self, x, gt):
        self.train()
        return self.step(x, gt)
    

# Training Loop
device = "cuda"
max_epochs = 100000

x = torch.load("x.pt").to(device)
gt = torch.load("gt.pt").to(device)

monotonic_model = MonotonicNN()
monotonic_model.to(device)
optimizer = optim.Adam(monotonic_model.parameters(), lr=1e-3)

for i in tqdm(range(0, max_epochs)):
    optimizer.zero_grad()

    loss = monotonic_model.training_step(x, gt)

    loss.backward()
    optimizer.step()

```

**Comment by niklasnolte** [comment]
because each of your layers has a lipschitz constant of 100, the total lipschitz constant is 100^4, so your monotonic wrapper would need that as a lipschitz constant argument. Try 100**0.25 in each layer!

**Comment by okitouni** [comment]
Each individual layer can essentially multiply its input by a factor of up to 100. Stacking them will lead to a very large Lipschitz constant for the entire network. What you'd want is 100^(1/d) for a network of depth d. Closing the issue. Feel free to open again if something else remains unclear.
