### ISSUE TITLE
<dummy>

### ISSUE THREAD

**Issue by okitouni** [niklasnolte/MonotOneNorm#5]
This is a dummy issue to host figures.
![monotonic_dependence_unobserved_UpFalse_InterpFalse](https://github.com/niklasnolte/MonotonicNetworks/assets/28654657/db570a42-3483-4a02-93e9-e32c8d02eb18)
![robust_against_noisy_outlier](https://github.com/niklasnolte/MonotonicNetworks/assets/28654657/81dfbcc5-9ed7-4494-94fd-a692bb087c4f)
![flower](https://github.com/niklasnolte/MonotonicNetworks/assets/28654657/25604500-3720-4962-925b-b97aee8ee42c)

**Comment by niklasnolte** [comment]
thanks for raising this issue, fixed.
