### ISSUE TITLE
one-inf possible bug?

### ISSUE THREAD

**Issue by ctargon** [niklasnolte/MonotOneNorm#7]
in get_normed_weights, should the one-inf option be:

norms = weights.abs().max()

? It seems to me that, according to the paper's definition of one-inf matrix norm, the one-inf norm would only be correct if vectorwise=False. However, in the examples notebook "one-inf" is used when vectorwise=True.

**Comment by niklasnolte** [comment]
vectorwise for one-inf should really be called elementwise..

so, for elementwise=True, we would like each element to be unrestricted until it hits the bound. For weight.abs().max(), everything would be divided by the max, thus smaller elements are also affected.

does that track with your understanding?

**Comment by ctargon** [comment]
that makes sense. thanks for the help!
