### ISSUE TITLE
non-negative constraint via relu

### ISSUE THREAD

**Issue by TingdiRen** [niklasnolte/MonotOneNorm#9]
Since my goal contains the constraint that the output is non-negative, I would like to add relu to the last layer, however this seems to break the lipschitz-1 continuum. Is there a good solution for this? Thank you for your reply.

**Comment by niklasnolte** [comment]
adding a relu to the output at the very end should work, after the residual has been added.

You could make another module:

```python
class PositiveMonotonicWrapper(MonotonicWrapper):
  def forward(self, x):
    x = super().forward(x)
    return torch.nn.functional.relu(x)
  
```

**Comment by TingdiRen** [comment]
Thank you for your prompt response. I have found that the violation of the Lipschitz constraint after adding ReLU was due to some long-standing overlooked bugs in the code. Hence the solution provided above appears to be effective. Finally, sincere thanks for this research, especially for your commitment to open-sourcing and maintaining the code.  :)👍
